# -*- coding: utf-8 -*-
"CV_WEB_Object_Detection_YOLOV8.ipynb

Automatically generated by Collaboratory.

The original file is located at
    https://colab.research.google.com/drive/1hLLS7OfvIrHTnmEeWM1mf5iM7FBUj99b
"""

# importing the required libraries
import os
HOME = os.getcwd()
print(HOME)

# connected to processor
!nvidia-smi

# Install these dependencies before running this code
!pip install ultralytics==8.0.20

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO V8

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO V8

!yolo task = detect mode = train model = yolov8l.pt data = data.yaml epochs = 50 imgsz = 640

!yolo task = detect mode = val model = runs/detect/train11/weights/best.pt data = data.yaml

!yolo task = detect mode = predict model = runs/detect/train11/weights/best.pt conf = 0.25 source = data/Test\ Dataset\ 1

!yolo task = detect mode = predict model = runs/detect/train4/weights/best.pt conf = 0.25 source = data/Test\ Dataset\ 2

